obstacle_range: 3.0 # 0-3.0 MARK
raytrace_range: 3.2 # 3.2+ CLEAR
#max_obstacle_height: 2

footprint: [[-0.35, -0.275], [-0.35, 0.275], [0.35, 0.275], [0.35, -0.275]]
#robot_radius: 0.105

inflation_radius: 0.55
cost_scaling_factor: 5.0

map_type: costmap
#observation_sources: scan
#scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}