obstacle_range: 2.5 # 0-2.5 MARK
raytrace_range: 2.6 # 2.6+ CLEAR
#max_obstacle_height: 2

footprint: [[-0.35, -0.275], [-0.35, 0.275], [0.35, 0.275], [0.35, -0.275]]
#robot_radius: 0.105

inflation_radius: 0.55
cost_scaling_factor: 5.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
